module __gpio8__gpio_tick(
  input wire [63:0] state,
  input wire [21:0] bus_in,
  output wire [88:0] out
);
  wire [7:0] bus_in_pins_in;
  wire [7:0] state_data_out__1;
  wire [7:0] state_dir__2;
  wire [3:0] bus_in_addr__1;
  wire [7:0] state_pin_prev__1;
  wire [7:0] actual_pins;
  wire [2:0] bit_idx;
  wire [7:0] state_irq_rise__1;
  wire [7:0] state_irq_en__1;
  wire [7:0] state_irq_fall__1;
  wire [7:0] bus_in_data_in;
  wire [7:0] mask;
  wire [7:0] state_irq_status__1;
  wire [7:0] rise_irqs;
  wire [7:0] fall_irqs;
  wire [3:0] REG_IRQ_STATUS;
  wire [7:0] new_status;
  wire [3:0] REG_IRQ_EN;
  wire [3:0] REG_OUT_MODE;
  wire [3:0] REG_DATA_OUT;
  wire [3:0] REG_DATA_IN;
  wire [3:0] REG_DIR;
  wire [3:0] REG_IRQ_RISE;
  wire [3:0] REG_IRQ_FALL;
  wire [7:0] shrl_944;
  wire bus_in_wr;
  wire eq_946;
  wire eq_948;
  wire eq_949;
  wire eq_950;
  wire eq_953;
  wire eq_954;
  wire eq_955;
  wire [7:0] state_after_edge_out_mode;
  wire [8:0] concat_964;
  wire [7:0] state_after_write_irq_status;
  wire [7:0] state_after_write_irq_en;
  wire [7:0] state_after_write_out_mode;
  wire [7:0] state_after_write_data_out;
  wire bus_in_rd;
  wire [7:0] state_after_write_dir;
  wire [7:0] data_out;
  wire irq;
  wire [7:0] pins_oe;
  wire [63:0] state_after_write;
  wire [24:0] output__1;
  assign bus_in_pins_in = bus_in[7:0];
  assign state_data_out__1 = state[63:56];
  assign state_dir__2 = state[55:48];
  assign bus_in_addr__1 = bus_in[21:18];
  assign state_pin_prev__1 = state[7:0];
  assign actual_pins = state_data_out__1 & state_dir__2 | ~(~bus_in_pins_in | state_dir__2);
  assign bit_idx = bus_in_addr__1[2:0];
  assign state_irq_rise__1 = state[31:24];
  assign state_irq_en__1 = state[39:32];
  assign state_irq_fall__1 = state[23:16];
  assign bus_in_data_in = bus_in[17:10];
  assign mask = 8'h01 << bit_idx;
  assign state_irq_status__1 = state[15:8];
  assign rise_irqs = actual_pins & ~state_pin_prev__1 & state_irq_rise__1 & state_irq_en__1;
  assign fall_irqs = ~actual_pins & state_pin_prev__1 & state_irq_fall__1 & state_irq_en__1;
  assign REG_IRQ_STATUS = 4'h6;
  assign new_status = state_irq_status__1 | rise_irqs | fall_irqs;
  assign REG_IRQ_EN = 4'h3;
  assign REG_OUT_MODE = 4'h7;
  assign REG_DATA_OUT = 4'h0;
  assign REG_DATA_IN = 4'h1;
  assign REG_DIR = 4'h2;
  assign REG_IRQ_RISE = 4'h4;
  assign REG_IRQ_FALL = 4'h5;
  assign shrl_944 = state_data_out__1 >> bit_idx;
  assign bus_in_wr = bus_in[8:8];
  assign eq_946 = bus_in_addr__1 == REG_IRQ_STATUS;
  assign eq_948 = bus_in_addr__1 == REG_IRQ_EN;
  assign eq_949 = bus_in_addr__1 == REG_OUT_MODE;
  assign eq_950 = bus_in_addr__1 == REG_DATA_OUT;
  assign eq_953 = bus_in_addr__1 == REG_DIR;
  assign eq_954 = bus_in_addr__1 == REG_IRQ_RISE;
  assign eq_955 = bus_in_addr__1 == REG_IRQ_FALL;
  assign state_after_edge_out_mode = state[47:40];
  assign concat_964 = {eq_950, bus_in_addr__1 == REG_DATA_IN, eq_953, eq_948, eq_954, eq_955, eq_946, eq_949, bus_in_addr__1[3]};
  assign state_after_write_irq_status = ~(bus_in_wr & eq_946) ? new_status : ~(~new_status | bus_in_data_in);
  assign state_after_write_irq_en = ~(bus_in_wr & eq_948) ? state_irq_en__1 : bus_in_data_in;
  assign state_after_write_out_mode = ~(bus_in_wr & eq_949) ? state_after_edge_out_mode : bus_in_data_in;
  assign state_after_write_data_out = bus_in_wr ? (eq_950 ? bus_in_data_in : (bus_in_addr__1[3] ? (bus_in_data_in[0] ? state_data_out__1 | mask : ~(~state_data_out__1 | mask)) : state_data_out__1)) : state_data_out__1;
  assign bus_in_rd = bus_in[9:9];
  assign state_after_write_dir = ~(bus_in_wr & eq_953) ? state_dir__2 : bus_in_data_in;
  assign data_out = bus_in_rd ? {7'h00, shrl_944[0]} & {8{concat_964[0]}} | state_after_edge_out_mode & {8{concat_964[1]}} | new_status & {8{concat_964[2]}} | state_irq_fall__1 & {8{concat_964[3]}} | state_irq_rise__1 & {8{concat_964[4]}} | state_irq_en__1 & {8{concat_964[5]}} | state_dir__2 & {8{concat_964[6]}} | actual_pins & {8{concat_964[7]}} | state_data_out__1 & {8{concat_964[8]}} : 8'hff;
  assign irq = (state_after_write_irq_status & state_after_write_irq_en) != 8'h00;
  assign pins_oe = state_after_write_dir & ~(state_after_write_out_mode & state_after_write_data_out);
  assign state_after_write = {state_after_write_data_out, state_after_write_dir, state_after_write_out_mode, state_after_write_irq_en, ~(bus_in_wr & eq_954) ? state_irq_rise__1 : bus_in_data_in, ~(bus_in_wr & eq_955) ? state_irq_fall__1 : bus_in_data_in, state_after_write_irq_status, actual_pins};
  assign output__1 = {data_out, irq, state_after_write_data_out, pins_oe};
  assign out = {state_after_write, output__1};
endmodule
